### PR TITLE
Number of custom hostname fixes

### PR DESCRIPTION
**Pull request by mrtristan**
Missing some statuses - can't list my hostnames as they're mostly in an "active" state which isn't a listed value of the current enum so it just throws an exception

image

missing setter yields null on deserialization:
image

added a number of additional properties- Cloudflare API docs seem to be incorrect vs actual API responses - started by modeling against docs then had to pivot hierarchy to reflect levels where properties actually exist.

### CODE REVIEW

**Comment by mrtristan** [comment]
@zingz0r please take a look here when you can - thanks

**Comment by zingz0r** [comment]
> @zingz0r please take a look here when you can - thanks

Sorry, I'm swamped nowadays. I will check it on the following Monday.

**Review by zingz0r — APPROVED** [review]

**Review by zingz0r — APPROVED** [review]

**Pull request merged**
