### PR TITLE
Added "enterprise" as possible list of values that can be deserialized

### PR DESCRIPTION
**Pull request by jasonmwebb-lv**
Added "enterprise" as possible list of values that can be deserialized to AccountType enum. Added unit test to assert that deserialization works for this new enum.

### CODE REVIEW

**Comment by jasonmwebb-lv** [comment]
@zingz0r  could you take a look at this PR?

**Review by zingz0r — APPROVED** [review]

**Review by zingz0r — CHANGES_REQUESTED** [review]
https://github.com/zingz0r/CloudFlare.Client/blob/master/CloudFlare.Client.Test/Serialization/Enumerators/AccountTypeTest.cs should be adjusted regarding the newly added enterprise account type

**Comment by zingz0r** [comment]
#58

**Review by zingz0r — APPROVED** [review]

**Pull request merged**
