### PR TITLE
start of implementing filter endpoints

### PR DESCRIPTION
**Pull request by mrtristan**
getting started building out filters and firewall rules. before i go too far just wanted to check in and make sure this is something you'll accept if i keep going with it. trying to maintain the patterns you've established but i may separately PR some further refinements.

https://api.cloudflare.com/#firewall-rules-delete-individual-firewall-rules

### CODE REVIEW

**Comment by mrtristan** [comment]
@zingz0r let me know if there is anything objectionable here or if you won't be able to review this soon. will need to potentially host a version if so to keep my project going. thanks!

**Comment by zingz0r** [comment]
@mrtristan Thanks for creating this PR.  I'll check it on the weekend.

**Review by zingz0r — APPROVED** [review]

**Pull request merged**
