### PR TITLE
Feature/ssl always use https

### PR DESCRIPTION
**Pull request by jasonmwebb-lv**
Added ability to [set ](https://api.cloudflare.com/#zone-settings-change-always-use-https-setting)and [get ](https://api.cloudflare.com/#zone-settings-get-always-use-https-setting)"AlwaysUseHttps" settings of zone

### CODE REVIEW

**Comment by JasonMWebb** [comment]
@zingz0r Could you take a look at this?

**Review by JasonMWebb — APPROVED** [review]

**Comment by zingz0r** [comment]
> @zingz0r Could you take a look at this?

Yep, will check it on the weekend

**Pull request merged**
