### PR TITLE
Added support for DNS records comments

### PR DESCRIPTION
**Pull request by Et3rnos**
Added a new field in NewDnsRecord.cs for the record comment.

### CODE REVIEW

**Comment by zingz0r** [comment]
Please update corresponfing tests

**Comment by Et3rnos** [comment]
Updated the tests

**Comment by Et3rnos** [comment]
Not sure of what the problem is, all of the tests passed.

**Comment by zingz0r** [comment]
I need to upgrade the pipeline which I'll do as soon as I'll have time. Should nothing be wrong with this PR.

**Pull request merged**
